name: Deploy Docker Hub
# Only activate on a push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log into docker with my account
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image for all items
        run: |
          docker build -t ugo21/multi-client ./client
          docker build -t ugo21/multi-nginx ./nginx
          docker build -t ugo21/multi-server ./server
           docker build -t ugo21/multi-worker ./worker

      - name: Push all the docker images to docker hub
      - run: |
          docker push ugo21/multi-client
          docker push ugo21/multi-nginx
          docker push ugo21/multi-server
          docker push ugo21/multi-worker
