name: Deploy to Docker Hub
# Only activate on a push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log into docker with my account
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image for client
        run: docker build -t ugo21/multi-client ./client
      - name: Build docker image for nginx
        run: docker build -t ugo21/multi-nginx ./nginx
      - name: Build docker image for server
        run: docker build -t ugo21/multi-server ./server
      - name: Build docker image for worker
        run: docker build -t ugo21/multi-worker ./worker

      - name: Push client docker image to docker hub
        run: docker push ugo21/multi-client
      - name: Push nginx docker image to docker hub
        run: docker push ugo21/multi-nginx
      - name: Push server docker image to docker hub
        run: docker push ugo21/multi-server
      - name: Push worker docker image to docker hub
        run: docker push ugo21/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env-1
          existing_bucket_name: elasticbeanstalk-ca-central-1-602651683030
          version_label: 1
          region: ca-central-1
          deployment_package: deploy.zip
